## Problem 6

In [25]:
# Imports
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import pandas
import math
import matplotlib.pyplot as plt

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [39]:
# Load data
data = pandas.read_excel('data.xls')

X1 = data.to_numpy()[:, 0].reshape(-1, 1)
X2 = data.to_numpy()[:, 1].reshape(-1, 1)
X3 = data.to_numpy()[:, 2].reshape(-1, 1)
y = data.to_numpy()[:, 3]

# For logistic regression, our "true" case is when the value of the final exam is >=160.
y = [1 if i >= 160 else 0 for i in y]

# Iterate through different X values and fit logistic predictors based off of them
for X in [X1, X2, X3]:
    model = LogisticRegression(solver="lbfgs")
    model.fit(X, y)
    y_predict = model.predict(X)
    print("Confusion matrix: ")
    print(confusion_matrix(y_predict, y))
    
    # Calculate likelihood
    proba = 0
    for p in model.predict_proba(X):
        proba += math.log(max(p)) # For each value, sum the logs of probabilities of the predicted class (class that dataooint has the most probability of being in)
    print("Log Likelihood: ", proba)



*** No CODEPAGE record, no encoding_override: will use 'ascii'
Confusion matrix: 
[[11  1]
 [ 1 12]]
Log Likelihood:  -2.769951122944561
Confusion matrix: 
[[10  2]
 [ 2 11]]
Log Likelihood:  -5.328505682361494
Confusion matrix: 
[[12  0]
 [ 0 13]]
Log Likelihood:  -0.19848263055374357


### Problem 6B

In [43]:
# Iterate through different X values and fit linear predictors based off of them
X1X2 = data.to_numpy()[:, 0:2]
X1X3 = data.to_numpy()[:, 0:3:2]
X2X3 = data.to_numpy()[:, 1:3]

for X in [X1X2, X1X3, X2X3]:
    model = LogisticRegression(solver='lbfgs')
    model.fit(X, y)
    y_predict = model.predict(X)
    print("Confusion matrix: ")
    print(confusion_matrix(y_predict, y))
    
    # Calculate likelihood
    proba = 0
    for p in model.predict_proba(X):
        proba += math.log(max(p)) # For each value, sum the logs of probabilities of the predicted class (class that dataooint has the most probability of being in)
    print("Log Likelihood: ", proba)

    

Confusion matrix: 
[[11  1]
 [ 1 12]]
Log Likelihood:  -2.7390000726429484
Confusion matrix: 
[[12  0]
 [ 0 13]]
Log Likelihood:  -0.16441273292944347
Confusion matrix: 
[[12  0]
 [ 0 13]]
Log Likelihood:  -0.17080621142402583


### Problem 6C

In [45]:
X = data.to_numpy()[:, :]
model = LogisticRegression(solver='lbfgs')
model.fit(X, y)
y_predict = model.predict(X)
print("Confusion matrix: ")
print(confusion_matrix(y_predict, y))

# Calculate likelihood
proba = 0
for p in model.predict_proba(X):
    proba += math.log(max(p)) # For each value, sum the logs of probabilities of the predicted class (class that dataooint has the most probability of being in)
print("Log Likelihood: ", proba)


Confusion matrix: 
[[12  0]
 [ 0 13]]
Log Likelihood:  -0.06370647181475075


### Problem 6D
In the case of logistic regression with the threshold for passing set at 160, all models that include X3 correctly classify all points in the data set. Based just on performance, we might conclude that this means the model that uses ONLY X3 is the best, because we typically want the simplest model that performs the best. However, according to our BICs, there is still weak evidence that the classifier using all three (X1, X2, and X3) is still the best choice.